echo "Welcome to Commiter gear ⚙️"
echo "With this utility your commits will go up to the next level"
echo "------------------------------------------"
echo "This app have to modes of commit: "
echo "------------------------------------------"
echo "1. command gs (Gear Second): the fast commit with type commit and message"
echo "Exemple: ✨feat: This is a fast commit 🤗"
echo "------------------------------------------"
echo "2. command gt (Gear third): the bigger commit with type, scope and message"
echo "Exemple: ✨feat(commit): This is a bit commit 🤗"
echo "------------------------------------------"
echo "3. command gp (Gomu Gomu no Jet Pistol): this command is to fast push your commits to remote repository with current branch name"
echo "Lets push 😎"
echo "------------------------------------------"
echo "4. command gp (Gomu Gomu no Jet Rocket): this command is to fast pull to remote repository with current branch name"
echo "Lets pull 😎"
echo "------------------------------------------"
echo "4. command haki to show branch and commit infos (status, logs, branchs)"
echo "haki 👀"
echo "------------------------------------------"
echo "Try this two powerful modes, see next time"
echo "🤗 now push your commits, bye"
