echo "Welcome to Commiter gear ⚙️"
echo "With this utility your commits will go up to the next level"
echo "------------------------------------------"
echo "This app have to modes of commit: "
echo "------------------------------------------"
echo "1. command gs (Gear Second): the fast commit with type commit and message"
echo "Exemple: ✨feat: This is a fast commit 🤗"
echo "------------------------------------------"
echo "2. command gt (Gear third): the bigger commit with type, scope and message"
echo "Exemple: ✨feat(commit): This is a bit commit 🤗"
echo "------------------------------------------"
echo "Try this two powerful modes, see next time"
echo "🤗 now push your commits, bye"
